# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-15 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_buddy', '0002_auto_20191115_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='joined_by',
            field=models.ManyToManyField(null=True, related_name='join', to='login.User'),
        ),
    ]
